# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('introduce', models.CharField(max_length=50, verbose_name='商品简介')),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.IntegerField(default=1, verbose_name='数量')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='goods', verbose_name='图片')),
                ('key', models.CharField(default=' ', max_length=20, verbose_name='关键字')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名称：')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('sex', models.CharField(default='男', max_length=5, verbose_name='性别')),
                ('address', models.CharField(default=' ', max_length=50, verbose_name='收件地址')),
                ('hobby', models.CharField(default=' ', max_length=20, verbose_name='爱好')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.User'),
        ),
    ]
