# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('msg', models.CharField(max_length=2000, verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.User')),
            ],
            options={
                'verbose_name': '帖子信息',
                'db_table': 'stc_topic_info',
            },
        ),
    ]
