# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150, verbose_name='评论')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.User')),
            ],
        ),
    ]
