# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-04 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论信息'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='forum_comment',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='forum_topic',
        ),
    ]
