# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='接受者')),
                ('msg', models.CharField(max_length=50, verbose_name='信息内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='购买者')),
                ('good_id', models.CharField(max_length=20, verbose_name='商品')),
                ('user_id2', models.CharField(max_length=20, verbose_name='发布者')),
                ('price', models.CharField(max_length=20, verbose_name='价格')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=30, verbose_name='订单号')),
                ('address', models.CharField(max_length=20, verbose_name='地址')),
            ],
        ),
    ]
