# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-04 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msg',
        ),
    ]
