# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-04 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='接受者')),
                ('user_id2', models.CharField(max_length=20, verbose_name='发布者')),
                ('msg', models.CharField(max_length=50, verbose_name='信息内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
