# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-05 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
    ]
